- name: install mesosphere keys
  apt_key: keyserver=hkp://keyserver.ubuntu.com:80 id=E56151BF

- name: add mesosphere repo
  apt_repository: repo="deb http://repos.mesosphere.com/ubuntu trusty main"

- name: install mesos
  apt: name=mesos

- name: install marathon
  apt:
    name: marathon=1.3.10-1.0.627.ubuntu1404


- name: start zookeeper
  service: name=zookeeper state=restarted enabled=yes
